GOOGLE_API_KEY      = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
SEARCH_ENGINE_ID    = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
APIKEY              = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
myconfig            = r"--psm 12 oem 3"

host                = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
dbUser              = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
dbPassword          = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
database            = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"